# Generated by Django 4.2.19 on 2025-07-04 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_authenticated_user_guest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mute_microphone_on_join', models.BooleanField(default=False, help_text="Automatically mute the user's microphone when they join a meeting.")),
                ('turn_off_video_on_join', models.BooleanField(default=False, help_text="Automatically turn off the user's video when they join a meeting.")),
                ('enable_audio_translation', models.BooleanField(default=False, help_text='Enable automatic audio translation during meetings.')),
                ('enable_caption_translation', models.BooleanField(default=False, help_text='Enable automatic translation of closed captions.')),
                ('receive_meeting_reminders', models.BooleanField(default=True, help_text='Receive a notification 10 minutes before a meeting starts.')),
                ('user', models.OneToOneField(help_text='The user these settings belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Setting',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
