# Generated by Django 4.2.19 on 2025-04-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_authenticated',
        ),
        migrations.AddField(
            model_name='user',
            name='guest',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('AR', 'Arabic'), ('EN', 'English')], default='AR', max_length=50),
        ),
    ]
