# Generated by Django 4.2.19 on 2025-06-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meeting_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='started',
        ),
    ]
