# Generated by Django 4.2.19 on 2025-05-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='day',
            field=models.CharField(default='Saturday', max_length=10),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_time',
            field=models.TimeField(),
        ),
    ]
