# Generated by Django 4.2.19 on 2025-06-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_roommember'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
