# Generated by Django 4.2.19 on 2025-06-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_remove_meeting_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
