# Generated by Django 4.2.23 on 2025-06-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_day_alter_meeting_meeting_time'),
        ('meetings', '0005_meeting_is_started'),
    ]

    operations = [
    ]
